---
- name: Install and configure MariaDB
  hosts: master
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    mariadb_root_password: "parkings"
    mariadb_database: "parkings"
    mariadb_user: "parkings"
    mariadb_password: "parkings"

  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Ensure MariaDB is running and enabled on boot
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pymysql

    - name: Set MariaDB root password
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      ignore_errors: true

    - name: Create database
      mysql_db:
        name: "{{ mariadb_database }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Create database user
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_password }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
